
    <div id='login_form'>
        <form action='<?php echo base_url();?>user/process' method='post' name='process'>
            
            <input type="hidden" name="redirect" value="<?php $redirect; ?>" />
             
            <label for='username'>Username</label>
            <input type='text' name='username' /><br />
        
            <label for='password'>Password</label>
            <input type='password' name='password' /><br />                            
        
            <input type='Submit' value='Login' />            
        </form>
    </div>