<html>
<head>
	<title><?php echo(@$title ? $title .' - ' : false) ?>This is my Blog</title>
    <?php echo link_tag('css/screen.css'); ?>
</head>
<body>
    <div class="container">
        <div class="main-header">
            <h1><?php echo(@$title ? $title : 'This is my Blog') ?></h1>
        </div>
        <div class="main-messages">
            <?php 
                if( ! empty($error)):
                    echo '<ul class="error">';
                    foreach($error AS $message):
                        echo "<li>$message</li>";
                    endforeach;
                    echo '</ul> ';
                endif
            ?>
            <?php 
                if( ! empty($success)):
                    echo '<ul class="success">';
                    foreach($success AS $message):
                        echo "<li>$message</li>";
                    endforeach;
                    echo '</ul> ';
                endif
            ?>
        </div>
        <div class="main-navigation">
            <ul>
                <li><a href="">link 1</a></li>
                <li><a href="">link 2</a></li>
                <li><a href="">link 3</a></li>
                <li><a href="">link 4</a></li>
                <li><a href="">link 5</a></li>
            </ul>
        </div>
        <div class="main-content">
            <?php echo($layout_content); ?>
        </div>
        <div class="main-footer">
            <?php if($this->session->is_validated()){
                echo '<p>welcome, ' . $this->session->userdata('first_name') . ' | ';
                echo anchor('user/logout','logout');
                echo '<br />';
                echo anchor('user/manage','manage users');
                echo '</p>';
            } ?>
            <br />
            <strong>&copy; Odder Otter 2014</strong>
        </div>
    </div>
</body>
</html>